import localFont from "next/font/local";
import "./globals.css";
import { Metadata } from "next";

const offerFlowFont = localFont({
  src: "../public/fonts/offerflow.woff2",
  variable: "--font-offerflow",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${offerFlowFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
